remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: [KOFI!]
logo: kofimeighan/fatherkofi/docs/assets/IMG_7228.png
description: An archive of all mixes/performances in New York City.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
