remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: [KOFI!]
logo: docs/assets/IMG_1731.jpg
description:
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
