remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: [KOFI!]
logo: docs/assets/IMG_1731.jpg
description: From West palm Beach, Florida I am a currently a student at Columbia University studying Computer Science and Electrical Engineering. I’m interested in bringing unique mixes of hip-hop, r&b, soul, vapor trap, pluggnb, and so many more genres to the streets of New York City. This page is a musical journal of all my archived mixes and performances.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
